# -*- coding: utf-8 -*-
"""EXPLORATORY DATA ANALYSIS TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOW1VEpybixTtFE9LNYgftxiHZZxhQ2Y
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("iris.csv")

df.head()

df.tail()

df.info()

df.isnull().sum()

df.describe()

df.columns

plt.figure(figsize=(6,4))
plt.hist(df['sepal_length'], bins=10)
plt.title("Distribution of Sepal Length")
plt.xlabel("Sepal Length")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(6,4))
df['species'].value_counts().plot(kind='bar')
plt.title("Species Count")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(6,4))
plt.scatter(df['sepal_length'], df['petal_length'])
plt.title("Sepal Length vs Petal Length")
plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x=df['sepal_length'])
plt.title("Box Plot of Sepal Length")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
sns.countplot(x='species', data=df)

plt.title("Number of Samples in Each Species")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()

"""## Exploratory Data Analysis Report

1. The Iris dataset contains three flower species.
2. Most flowers have similar sepal length values.
3. Each species has an equal number of samples.
4. The scatter plot shows a positive relationship between sepal length and petal length.
5. No major missing values were found in the dataset.

## Exploratory Data Analysis Report

1. The Iris dataset contains 150 flower samples with 5 columns: four numerical features (`sepal_length`, `sepal_width`, `petal_length`, `petal_width`) and one categorical feature (`species`).

2. The dataset contains three flower species: Iris-setosa, Iris-versicolor, and Iris-virginica.

3. The species distribution is balanced, with 50 samples for each species.

4. The statistical analysis shows that flower measurements have different ranges, with petal length and petal width showing more variation compared to sepal measurements.

5. The scatter plot between sepal_length and petal_length shows a positive relationship, where flowers with higher sepal length generally have higher petal length.

6. The visualization shows that petal features provide better separation between species compared to sepal features.

7. The dataset was checked for missing values, and no missing values were found.

8. The box plot analysis shows that there are no major data quality issues in the dataset.

### Conclusion:
The Iris dataset is clean and balanced, making it suitable for machine learning classification tasks. The EDA results help in understanding patterns and relationships between flower features and species classification.
"""